import { StyleSheet } from 'react-native';
import { theme } from '../../../../assets/styles';

export const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: theme.colors.background.page,
    },
    container: {
        flex: 1,
        backgroundColor: theme.colors.background.page,
    },
    header: {
        backgroundColor: theme.colors.background.card,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: theme.spacing[4],
        paddingHorizontal: theme.spacing[4],
    },
    headerButton: {
        width: 40,
        height: 40,
        padding: theme.spacing[2],
    },
    headerIconImage: {
        width: 24,
        height: 24,
    },
    headerTitle: {
        fontSize: theme.typography.size.lg,
        lineHeight: theme.typography.lineHeight.lg,
        color: theme.colors.text.primary,
        fontWeight: theme.typography.weight.semibold,
    },
    scroll: {
        flex: 1,
    },
    contentContainer: {
        paddingTop: theme.spacing[4],
        paddingHorizontal: theme.spacing[4],
        paddingBottom: theme.spacing[16],
        gap: theme.spacing[6],
    },
    identityCard: {
        backgroundColor: theme.colors.background.card,
        borderRadius: theme.radius.xl,
        alignItems: 'center',
        paddingTop: theme.spacing[6],
        paddingBottom: theme.spacing[6],
        paddingHorizontal: 106,
        ...theme.shadow.md,
    },
    avatarWrapper: {
        width: 96,
        height: 112,
        padding: theme.spacing[4],
        alignItems: 'center',
        justifyContent: 'center',
    },
    avatarInner: {
        width: 96,
        height: 96,
        borderRadius: theme.radius.full,
        alignItems: 'center',
        justifyContent: 'center',
    },
    avatarImage: {
        width: '100%',
        height: '100%',
    },
    editAvatarBadge: {
        position: 'absolute',
        right: 0,
        bottom: theme.spacing[2],
        width: 32,
        height: 32,
        borderRadius: theme.radius.full,
        borderWidth: 2,
        borderColor: theme.colors.background.card,
        backgroundColor: theme.colors.brand.primary,
        alignItems: 'center',
        justifyContent: 'center',
    },
    editAvatarImage: {
        width: '55%',
        height: '55%',
    },
    nameText: {
        fontSize: theme.typography.size.xl,
        lineHeight: theme.typography.lineHeight.lg,
        color: theme.colors.text.heading,
        fontWeight: theme.typography.weight.bold,
        marginBottom: 2,
        textAlign: 'center',
    },
    usernameText: {
        fontSize: theme.typography.size.base,
        lineHeight: theme.typography.lineHeight.sm,
        color: theme.colors.text.muted,
        paddingBottom: theme.spacing[2],
    },
    memberBadge: {
        backgroundColor: theme.colors.brand.subtle,
        borderRadius: theme.radius.full,
        paddingHorizontal: theme.spacing[3],
        paddingVertical: theme.spacing[1],
    },
    memberBadgeText: {
        color: theme.colors.brand.primary,
        fontSize: theme.typography.size.xs,
        lineHeight: theme.typography.lineHeight.xs,
        fontWeight: theme.typography.weight.bold,
        letterSpacing: 0.6,
    },
    detailsCard: {
        backgroundColor: theme.colors.background.card,
        borderRadius: theme.radius.xl,
        paddingHorizontal: theme.spacing[6],
        paddingTop: theme.spacing[6],
        paddingBottom: theme.spacing[10],
        ...theme.shadow.md,
    },
    detailsHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: theme.spacing[6],
    },
    detailsTitle: {
        fontSize: theme.typography.size.lg,
        lineHeight: theme.typography.lineHeight.lg,
        color: theme.colors.text.primary,
        fontWeight: theme.typography.weight.semibold,
    },
    editDetailsText: {
        fontSize: theme.typography.size.base,
        lineHeight: theme.typography.lineHeight.sm,
        color: theme.colors.brand.primary,
        fontWeight: theme.typography.weight.semibold,
    },
    fieldBlock: {
        marginBottom: theme.spacing[4],
    },
    fieldLabel: {
        fontSize: theme.typography.size.xs,
        lineHeight: theme.typography.lineHeight.xs,
        color: theme.colors.text.disabled,
        fontWeight: theme.typography.weight.medium,
        letterSpacing: 0.3,
        marginBottom: theme.spacing[1],
    },
    emailFieldContainer: {
        borderRadius: theme.radius.xl,
        borderWidth: 1,
        borderColor: theme.colors.border.default,
        backgroundColor: theme.colors.background.page,
        paddingHorizontal: theme.spacing[3],
        paddingVertical: theme.spacing[2],
    },
    emailFieldValue: {
        fontSize: theme.typography.size.base,
        lineHeight: theme.typography.lineHeight.sm,
        color: theme.colors.text.muted,
    },
    fieldValue: {
        fontSize: theme.typography.size.base,
        lineHeight: theme.typography.lineHeight.sm,
        color: theme.colors.text.primary,
        paddingHorizontal: theme.spacing[3],
        paddingVertical: theme.spacing[2],
    },
    actionsContainer: {
        gap: theme.spacing[3],
    },
    actionCard: {
        backgroundColor: theme.colors.background.card,
        borderRadius: theme.radius.xl,
        padding: theme.spacing[4],
        ...theme.shadow.md,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    actionLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: theme.spacing[3],
    },
    orderIconBackground: {
        width: 36,
        height: 36,
        borderRadius: theme.radius.md,
        backgroundColor: theme.colors.background.muted,
        alignItems: 'center',
        justifyContent: 'center',
    },
    orderIcon: {
        width: 20,
        height: 20,
        tintColor: theme.colors.text.body,
    },
    orderIconText: {
        fontSize: theme.typography.size.md,
        lineHeight: theme.typography.lineHeight.sm,
        color: theme.colors.text.body,
    },
    actionLabel: {
        fontSize: theme.typography.size.md,
        lineHeight: theme.typography.lineHeight.md,
        color: theme.colors.text.body,
        fontWeight: theme.typography.weight.medium,
    },
    chevronIcon: {
        width: 20,
        height: 20,
        tintColor: theme.colors.border.muted,
    },
    logoutIconBackground: {
        width: 36,
        height: 36,
        borderRadius: theme.radius.md,
        padding: theme.spacing[2],
        backgroundColor: theme.colors.background.errorSubtle,
        alignItems: 'center',
        justifyContent: 'center',
    },
    logoutIcon: {
        width: 20,
        height: 20,
        tintColor: theme.colors.feedback.error,
    },
    logoutLabel: {
        fontSize: theme.typography.size.md,
        lineHeight: theme.typography.lineHeight.md,
        color: theme.colors.feedback.error,
        fontWeight: theme.typography.weight.medium,
    },
});

export default styles;
