import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: '#F9FAFB',
    },
    container: {
        flex: 1,
        backgroundColor: '#F9FAFB',
    },
    header: {
        backgroundColor: '#ffffff',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 16,
        paddingHorizontal: 16,
    },
    headerButton: {
        width: 40,
        height: 40,
        padding: 8,
    },
    headerIconImage: {
        width: 24,
        height: 24,
    },
    headerTitle: {
        fontSize: 18,
        lineHeight: 28,
        color: '#0F172A',
        fontWeight: '600',
    },
    scroll: {
        flex: 1,
    },
    contentContainer: {
        paddingTop: 16,
        paddingHorizontal: 16,
        paddingBottom: 64,
        gap: 24,
    },
    identityCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        alignItems: 'center',
        paddingTop: 24,
        paddingBottom: 24,
        paddingHorizontal: 106,
        shadowColor: '#000000',
        shadowOpacity: 0.06,
        shadowRadius: 20,
        shadowOffset: { width: 0, height: 4 },
        elevation: 9,
    },
    avatarWrapper: {
        width: 96,
        height: 112,
        padding: 16,
        alignItems: 'center',
        justifyContent: 'center',
    },
    avatarInner: {
        width: 96,
        height: 96,
        borderRadius: 9999,
        alignItems: 'center',
        justifyContent: 'center',
    },
    avatarImage: {
        width: '100%',
        height: '100%',
    },
    editAvatarBadge: {
        position: 'absolute',
        right: 0,
        bottom: 8,
        width: 32,
        height: 32,
        borderRadius: 9999,
        borderWidth: 2,
        borderColor: '#FFFFFF',
        backgroundColor: '#0DF2F2',
        alignItems: 'center',
        justifyContent: 'center',
    },
    editAvatarImage: {
        width: '55%',
        height: '55%',
    },
    nameText: {
        fontSize: 20,
        lineHeight: 28,
        color: '#1F2937',
        fontWeight: 'bold',
        marginBottom: 2,
        textAlign: 'center',
    },
    usernameText: {
        fontSize: 14,
        lineHeight: 20,
        color: '#6B7280',
        paddingBottom: 8,
    },
    memberBadge: {
        backgroundColor: '#0DF2F21A',
        borderRadius: 999,
        paddingHorizontal: 12,
        paddingVertical: 4,
    },
    memberBadgeText: {
        color: '#0DF2F2',
        fontSize: 12,
        lineHeight: 16,
        fontWeight: '700',
        letterSpacing: 0.6,
    },
    detailsCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        paddingHorizontal: 24,
        paddingTop: 24,
        paddingBottom: 40,
        shadowColor: '#000000',
        shadowOpacity: 0.05,
        shadowRadius: 20,
        shadowOffset: { width: 0, height: 4 },
        elevation: 3,
    },
    detailsHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 24,
    },
    detailsTitle: {
        fontSize: 18,
        lineHeight: 28,
        color: '#0F172A',
        fontWeight: '600',
    },
    editDetailsText: {
        fontSize: 14,
        lineHeight: 20,
        color: '#0DF2F2',
        fontWeight: '600',
    },
    fieldBlock: {
        marginBottom: 16,
    },
    fieldLabel: {
        fontSize: 12,
        lineHeight: 16,
        color: '#9CA3AF',
        fontWeight: '500',
        letterSpacing: 0.3,
        marginBottom: 4,
    },
    emailFieldContainer: {
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        backgroundColor: '#F9FAFB',
        paddingHorizontal: 12,
        paddingVertical: 8,
    },
    emailFieldValue: {
        fontSize: 14,
        lineHeight: 20,
        color: '#6B7280',
    },
    fieldValue: {
        fontSize: 14,
        lineHeight: 20,
        color: '#0F172A',
        paddingHorizontal: 12,
        paddingVertical: 8,
    },
    actionsContainer: {
        gap: 12,
    },
    actionCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        shadowColor: '#000000',
        shadowOpacity: 0.05,
        shadowRadius: 20,
        shadowOffset: { width: 0, height: 4 },
        elevation: 3,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    actionLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    orderIconBackground: {
        width: 36,
        height: 36,
        borderRadius: 8,
        backgroundColor: '#F1F5F9',
        alignItems: 'center',
        justifyContent: 'center',
    },
    orderIcon: {
        width: 20,
        height: 20,
        tintColor: '#374151',
    },
    orderIconText: {
        fontSize: 16,
        lineHeight: 20,
        color: '#374151',
    },
    actionLabel: {
        fontSize: 16,
        lineHeight: 24,
        color: '#374151',
        fontWeight: '500',
    },
    chevronIcon: {
        width: 20,
        height: 20,
        tintColor: '#D1D5DB',
    },
    logoutIconBackground: {
        width: 36,
        height: 36,
        borderRadius: 8,
        padding: 8,
        backgroundColor: '#FEF2F2',
        alignItems: 'center',
        justifyContent: 'center',
    },
    logoutIcon: {
        width: 20,
        height: 20,
        tintColor: '#EF4444',
    },
    logoutLabel: {
        fontSize: 16,
        lineHeight: 24,
        color: '#EF4444',
        fontWeight: '500',
    },
});

export default styles;
